#!/bin/bash

set -x
set -e
mount --rbind /host/dev /dev

frontend="tgt-blockdev"
data_server_protocol="tcp"

show_help() {
    cat << EOF
Usage: $(basename "$0") [option...]
Options:
  -h, --help		                        Show this help.
  -v, --volume <name>		                Volume name.
  -s, --size <size>		                    Volume size.
  -f, --frontend <tgt-blockdev|ublk>	    Frontend type.
  -p, --data-server-protocol <tcp|unix>     Data server protocol.
EOF
}

missing() {
    printf 'ERROR: Missing %s (%s)\n' "$1" "$2" >&2
    exit 2
}

while :; do
    case $1 in
	-h|--help)
	    show_help >&2
	    exit 0
	    ;;
	-v|--volume)
	    if [[ $2 ]]; then
		volume+=("$2")
		shift
	    else
		missing "volume" $1
	    fi
	    ;;
	-s|--size)
	    if [[ $2 ]]; then
		size+=("$2")
		shift
	    else
		missing "size" $1
	    fi
	    ;;
	-f|--frontend)
	    if [[ $2 ]]; then
		frontend+=("$2")
		shift
	    else
		missing "frontend" $1
	    fi
	    ;;
	-p|--data_server_protocol)
	    if [[ $2 ]]; then
		data_server_protocol+=("$2")
		shift
	    else
		missing "data-server-protocol" $1
	    fi
	    ;;
	--) shift; break ;;
	-?*) printf 'WARN: Ignoring unknown option %s\n' $1 >&2 ;;
	*) break ;;
    esac

    shift
done

# ============== main logic ==============
function start_grpc_health_probe() {
    set +e
    while true;
    do
        /usr/local/bin/grpc_health_probe -addr localhost:8500
        if [[ $? -eq 0 ]];
        then
            echo longhorn instance manager is ready
            break;
        fi
        sleep 1
    done
    set -e 
}

function start_tgtd() {
    tgtd -f 2>&1 | tee /var/log/tgtd.log &
}

function start_replica_process() {
    longhorn-instance-manager process create --name "$volume-r" --binary /usr/local/bin/longhorn --port-count 15 --port-args "--listen,localhost:" -- \
        replica /volume/ \
            --size $size \
            --data-server-protocol $data_server_protocol \
            --volume-name $volume
}

function start_engine_process() {
    longhorn-instance-manager process create --name "$volume-e" --binary /usr/local/bin/longhorn --port-count 1 --port-args "--listen,localhost:" -- \
        controller $volume \
            --frontend $frontend \
            --size $size \
            --current-size $size \
            --replica tcp://localhost:10000 \
            --data-server-protocol $data_server_protocol
}

function main() {
    start_grpc_health_probe
    start_tgtd

    start_replica_process

    # wait for the replica to be started
    sleep 5

    start_engine_process
}

main &

exec longhorn-instance-manager daemon
